# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ sandbox ]
  pull_request:
    branches: [ sandbox ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update OS
        run: |
          sudo apt update
          apt list --installed
          sudo apt install ksh curl wget

      - name: Install Ansible
        run: |
          sudo apt-get install python -y
          sudo apt-get install ansible -y

      - name: Check Version
        run: |
          ansible --version
          python --version
          python3 --version

      - name: clone repo
        run: git clone -b sandbox https://github.com/watsonops/ansible-code.git

      - name: Run sample playbook
        run: |
          ansible-playbook ansible-code/get_linux_info.yml
          
